### ISSUE TITLE
ugh

### ISSUE THREAD

**Issue by Super-toad65** [maorninja/Blargboard-XD#5]
is this secure to use? it seems that staple put a backdoor somewhere see http://rvlution.net/thread/4524-also-clarification-about-the-events/

and so, thad derp backdoor took me two suspended domains -.-

**Comment by maorninja** [comment]
It is.

There isn't any backdoor. That was for RVLution. He made something that ruined the board.

Also, its because you use byethost. Use X10 hosting.

**Comment by Super-toad65** [comment]
ugh ok
